sudo: required
dist: trusty
language: node_js
node_js:
  - "8"
before_install:
  - npm install request -g
  - yarn install
script:
  - yarn run test
cache:
  yarn: true
  directories:
    - node_modules
